import 'dart:async';
import 'dart:core';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:simple_date_picker/widget/simple_year_month_day_picker_widget.dart';
import 'package:simple_date_picker/widget/simple_year_month_picker_widget.dart';
import 'package:simple_date_picker/widget/simple_year_picker_widget.dart';

class SimpleDatePicker {
  StreamController<DateTime> yearMonthController = StreamController<DateTime>();
  DateTime yearMonthDateTime = DateTime.now();

  Widget yearPicker(
      {required final DateTime yearDateTime,
      required final Function(int) yearCallback,
      final int firstYear = 1900,
      final int lastYear = 2100,
      final Color? barrierColor = kCupertinoModalBarrierColor,
      final Decoration? decoration,
      final EdgeInsetsGeometry padding = EdgeInsets.zero,
      final double width = 400,
      final double height = 350,
      final double? yearWidth,
      final double yearHeight = 250,
      final Decoration? pickerDecoration,
      final Color pickerBackgroundColor = Colors.white,
      final double itemHeight = 60,
      final Alignment textAlignment = Alignment.center,
      final TextStyle? textStyle,
      final double buttonHeight = 60,
      final double todayButtonWidth = 200,
      final Color todayButtonColor = Colors.white,
      final Decoration? todayButtonDecoration,
      final String todayButtonText = 'TODAY',
      final TextStyle? todayButtonTextStyle =
          const TextStyle(color: Colors.black),
      final double doneButtonWidth = 200,
      final Color doneButtonColor = Colors.white,
      final Decoration? doneButtonDecoration,
      final String doneButtonText = 'DONE',
      final TextStyle? doneButtonTextStyle =
          const TextStyle(color: Colors.black)}) {
    return SimpleYearPickerWidget(
      onChangedCallback: yearCallback,
      yearDateTime: yearDateTime,
      firstYear: firstYear,
      lastYear: lastYear,
      barrierColor: barrierColor,
      decoration: decoration,
      padding: padding,
      width: width,
      height: height,
      yearWidth: yearWidth,
      yearHeight: yearHeight,
      pickerDecoration: pickerDecoration,
      pickerBackgroundColor: pickerBackgroundColor,
      itemHeight: itemHeight,
      textAlignment: textAlignment,
      textStyle: textStyle,
      buttonHeight: buttonHeight,
      todayButtonWidth: todayButtonWidth,
      todayButtonColor: todayButtonColor,
      todayButtonDecoration: todayButtonDecoration,
      todayButtonText: todayButtonText,
      todayButtonTextStyle: todayButtonTextStyle,
      doneButtonWidth: doneButtonWidth,
      doneButtonColor: doneButtonColor,
      doneButtonDecoration: doneButtonDecoration,
      doneButtonText: doneButtonText,
      doneButtonTextStyle: doneButtonTextStyle,
    );
  }

  Widget yearMonthPicker(
      {required final DateTime yearMonthDateTime,
  required final Function(int) monthCallback,
  required final Function(int) yearCallback,
  final int firstYear = 1900,
  final int lastYear = 2100,
  final Color barrierColor = kCupertinoModalBarrierColor,
  final Decoration? decoration,
  final EdgeInsetsGeometry padding = EdgeInsets.zero,
  final double width = 400,
  final double height = 350,
  final double monthWidth = 200,
  final double yearWidth = 200,
  final double pickerHeight = 250,
  final Decoration? pickerDecoration,
  final Color pickerBackgroundColor = Colors.white,
  final double itemHeight = 60,
  final Alignment textAlignment = Alignment.center,
  final TextStyle? monthTextStyle,
  final TextStyle? yearTextStyle,
  final double buttonHeight = 60,
  final double todayButtonWidth = 200,
  final Color todayButtonColor = Colors.white,
  final Decoration? todayButtonDecoration,
  final String todayButtonText = 'TODAY',
  final TextStyle? todayButtonTextStyle = const TextStyle(color: Colors.black),
  final double doneButtonWidth = 200,
  final Color doneButtonColor = Colors.white,
  final Decoration? doneButtonDecoration,
  final String doneButtonText = 'DONE',
  final TextStyle? doneButtonTextStyle = const TextStyle(color: Colors.black),}) {
    return SimpleYearMonthPickerWidget(
    yearMonthDateTime: yearMonthDateTime,
    monthCallback: monthCallback,
      yearCallback: yearCallback,
      firstYear: firstYear,
      lastYear: lastYear,
      barrierColor: barrierColor,
      decoration: decoration,
      padding: padding,
      width: width,
      height: height,
      monthWidth: monthWidth,
      yearWidth: yearWidth,
      pickerHeight: pickerHeight,
      pickerDecoration: pickerDecoration,
      pickerBackgroundColor: pickerBackgroundColor,
      itemHeight: itemHeight,
      textAlignment: textAlignment,
      monthTextStyle: monthTextStyle,
      yearTextStyle: yearTextStyle,
      buttonHeight: buttonHeight,
      todayButtonWidth: todayButtonWidth,
      todayButtonColor: todayButtonColor,
      todayButtonDecoration: todayButtonDecoration,
      todayButtonText: todayButtonText,
      todayButtonTextStyle: todayButtonTextStyle,
      doneButtonWidth: doneButtonWidth,
      doneButtonColor: doneButtonColor,
      doneButtonDecoration: doneButtonDecoration,
      doneButtonText: doneButtonText,
      doneButtonTextStyle: doneButtonTextStyle,
    );
  }

  Widget yearMonthDayPicker(
      {required final DateTime yearMonthDayDateTime,
        required final Function(int) monthCallback,
        required final Function(int) dayCallback,
        required final Function(int) yearCallback,
        final int firstYear = 1900,
        final int lastYear = 2100,
        final Color? barrierColor,
        final Decoration? decoration,
        final EdgeInsetsGeometry padding = EdgeInsets.zero,
        final double width = 400,
        final double height = 350,
        final double monthWidth = 120,
        final double dayWidth = 120,
        final double yearWidth = 160,
        final double pickerHeight = 250,
        final Decoration? pickerDecoration,
        final Color pickerBackgroundColor = Colors.white,
        final double itemHeight = 60,
        final Alignment textAlignment = Alignment.center,
        final TextStyle? monthTextStyle,
        final TextStyle? dayTextStyle,
        final TextStyle? yearTextStyle,
        final double buttonHeight = 60,
        final double todayButtonWidth = 200,
        final Color todayButtonColor = Colors.white,
        final Decoration? todayButtonDecoration,
        final String todayButtonText = 'TODAY',
        final TextStyle todayButtonTextStyle = const TextStyle(color: Colors.black),
        final double doneButtonWidth = 200,
        final Color doneButtonColor = Colors.white,
        final Decoration? doneButtonDecoration,
        final String doneButtonText = 'DONE',
        final TextStyle doneButtonTextStyle = const TextStyle(color: Colors.black),}) {
    return SimpleYearMonthDayPickerWidget(
      yearMonthDayDateTime: yearMonthDayDateTime,
      monthCallback: monthCallback,
      dayCallback: dayCallback,
      yearCallback: yearCallback,
      firstYear: firstYear,
      lastYear: lastYear,
      barrierColor: barrierColor,
      decoration: decoration,
      padding: padding,
      width: width,
      height: height,
      monthWidth: monthWidth,
      dayWidth: dayWidth,
      yearWidth: yearWidth,
      pickerHeight: pickerHeight,
      pickerDecoration: pickerDecoration,
      pickerBackgroundColor: pickerBackgroundColor,
      itemHeight: itemHeight,
      textAlignment: textAlignment,
      monthTextStyle: monthTextStyle,
      dayTextStyle: dayTextStyle,
      yearTextStyle: yearTextStyle,
      buttonHeight: buttonHeight,
      todayButtonWidth: todayButtonWidth,
      todayButtonColor: todayButtonColor,
      todayButtonDecoration: todayButtonDecoration,
      todayButtonText: todayButtonText,
      todayButtonTextStyle: todayButtonTextStyle,
      doneButtonWidth: doneButtonWidth,
      doneButtonColor: doneButtonColor,
      doneButtonDecoration: doneButtonDecoration,
      doneButtonText: doneButtonText,
      doneButtonTextStyle: doneButtonTextStyle,
    );
  }
}
